### ISSUE TITLE
Add block compression

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#10]
(placeholder)

Blocks are currently uncompressed. Compressing blocks should save on storage, reduce network overhead (at expense of CPU), and make things better.

https://github.com/facebook/rocksdb/wiki/Compression

**Comment by pragmaticanon** [comment]
Would love to take this up. Planning on implementing this in the following way:
1. Add `compression: Option<CompressionOptions>` as a field in `DbOptions`.
2. Add `fn compress` and `fn decompress` to `Block` and pass in c into `encode` and `decode`.
3. Make Snappy default compression algorithm.

**Comment by criccomini** [comment]
SGTM! Depending on the complexity of the compress/decompress code, might be worth having a `CompressionCodec` trait or something. I'll defer to you on that based on how things go when you implement.

**Comment by pragmaticanon** [comment]
The only issue I see is passing down compression type downstream in a lot of functions, not sure if there's a better way though.

**Comment by rodesai** [comment]
I'd suggest looking at doing compression/decompression from `SsTableFormat`. It should fit in quite naturally if you implement it that way. You can store an `Optional<CompressionCodec>` there and then use it if it's present to decompress blocks when reading. For the write path you'd have to have `SsTableFormat` pass the codec to `EncodedSsTableBuilder`. The benefit with this approach is that you don't have to introduce the concept of compression at the block or db level - the SST format just handles it transparently.

**Comment by criccomini** [comment]
https://github.com/slatedb/slatedb/pull/123

**Comment by criccomini** [comment]
Merged in #123
