### ISSUE TITLE
Notify clients when there is a failure

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#111]
Client puts and deletes don't have the opportunity to receive `SlateDBError::Fenced` errors. How do clients detect when they've been fenced?

**Comment by criccomini** [comment]
There is more discussion about this issue [on Discord](https://discord.com/channels/1232385660460204122/1277019372506054810/1277117276272857171). The general idea is that we have several background threads: WAL flusher, memtable flusher, and compaction. If errors occur on these threads, they die, but the user is never notified of the failure. They continue put'ing and get'ing and weird behavior can happen.

Per-the discussion, I think the easiest path forward is:

1. Introduce a `error: Option<SlateDbError>` in `DbState`.
2. Replace all `panic!()`'s by setting the `DbState` error.
3. Catch any errors in the base of the background threads (flush, memtable_flush, and compaction_executor/scheduler) and set the `DbState` error.
5. When set, the various user-facing APIs should return that error rather than proceeding with the method calls.

**Comment by dyedgreen** [comment]
Curios to pick this up unless anyone else is already looking at this?

**Comment by rishitc** [comment]
Hi @criccomini,
Thanks for sharing the resources on Discord. I looked at them earlier today and would like to work on this issue.

If @dyedgreen has yet to start, can I work on this?

Thanks

**Comment by criccomini** [comment]
@dyedgreen Looks like we had a race condition! 🤣 I've assigned the ticket to @rishitc as we've been talking about this issue on Discord a bit.

If you're looking for something else to take, perhaps #77 interests you? Or #163?

**Comment by dyedgreen** [comment]
Those two look good as well; happy to get started with #77 (from reading the issue that one seems a bit easier, so might be a better one to get started with?)

**Comment by rishitc** [comment]
@dyedgreen you should also join the [SlateDB Discord Server](https://discord.gg/mHYmGy5MgA) if you haven't already.
It would be great to have you there 🙂

**Comment by criccomini** [comment]
Documenting some Discord discussion:

> The primary assumption in my approach is that we only want to monitor failures in background threads. (at least in this issue) We are not concerned about respawning the failed thread.
> 
> With this assumption, the approach I have in mind is as follows:
> 1. We maintain a HashMap and a boolean error flag in the main thread of execution, which maps a background thread ID to its state.
>    1. This HashMap and boolean flags are shared with the background threads so that they can modify their corresponding entries and the boolean flag.
>    2. In this design, I'm assuming that we maintain different *Error enums for each type of thread so that it is easier to work with, i.e., The CompactionError enum will only have variants for errors the Compaction thread can face, etc.
> 2. If any background threads encounter an error, they set their corresponding entry in the HashMap with the appropriate error and set the boolean flag to true.
> 
> Notes:
> 1. The main motivation for the boolean error flag is to avoid having to interact with the map to check if an error exists.
>     1. However, one possible alternative that I also want to try is checking the size of the map to detect errors. The idea here is that in case of no errors the map should be empty and if there are errors, it should be non-empty.
> 
> When a user tries any DB operation, we can check the boolean flag and report that an internal server has occurred. To get diagnostic information about the failure, we can expose a new endpoint to filter the errors from the HashMap and return them.

@rodesai mentioned:

> I think at a high level this makes sense. Couple thoughts/questions:
> * what are you planning to use for thread IDs? The background work aren't all specifically threads. Some of the background work is run as async tasks. I think you'd probably want to use some sort of logical identifier like "wal flusher"/"memtable flusher"/"compactor".
> * how will we handle panics in the background tasks/threads? I guess we'd have 2 options. We can either wrap the root of the task in catch_unwind and then use the error signaling mechanism you described, or poll the task's join handle when checking for errors. I suspect the latter might be more expensive.

And the response from @rishitc:

>> what are you planning to use for thread IDs? The background work aren't all specifically threads. Some of the background work is run as async tasks. I think you'd probably want to use some sort of logical identifier like "wal flusher"/"memtable flusher"/"compactor".
> 
> My idea was to use the thread ID to identify the thread of execution, but in hindsight, it's much simpler to use a logical identifier 👍 
>
>> how will we handle panics in the background tasks/threads? I guess we'd have 2 options. We can either wrap the root of the task in catch_unwind and then use the error signaling mechanism you described, or poll the task's join handle when checking for errors. I suspect the latter might be more expensive.
>
> Frankly, I think the first option of using catch_unwind is better as we can ensure that we only run the code to save the error in the HashMap when a panic happens.
In comparison, polling the task join handle will burn CPU cycles, especially if the background thread does not encounter any errors.

**Comment by criccomini** [comment]
@palash25 want to take this one?

**Comment by palash25** [comment]
sure, this seems interesting.

**Comment by criccomini** [comment]
Assigned! :)

**Comment by palash25** [comment]
starting work on this

**Comment by criccomini** [comment]
@palash25 Checking in on this one

**Comment by palash25** [comment]
Sorry something came up this week. I will try to finish this up tomorrow or
day after if I can't make a PR by then we can have someone else try this

**Comment by calavera** [comment]
@criccomini yeah, feel free to assign it to me.

**Comment by criccomini** [comment]
@calavera I think this might be done. OK to close?

**Comment by calavera** [comment]
yeah, I think this is good to close.
