### ISSUE TITLE
Make a `DbOptions::default()`

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#113]
Similar to `WriteOptions` and `ReadOptions`, `DbOptions` should have a `::default()` method with sane settings.

**Comment by Jeadie** [comment]
I'll do this

**Comment by criccomini** [comment]
@Jeadie , thanks! Merged in your PR. :)

**Comment by criccomini** [comment]
Merged in https://github.com/slatedb/slatedb/pull/120
