### ISSUE TITLE
Invalid compaction on slow block writes

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#124]
While trying to replicate #121, I triggered the following error:

```
invalid compaction: Err(
    InvalidCompaction,
)
```

On this checksum: 47ab5dae0359bac41fd15adc423c3a7456ba12c0

The only changes I made to SlateDB's code was this:

```rust
--- a/src/tablestore.rs
+++ b/src/tablestore.rs
@@ -11,9 +11,11 @@ use object_store::buffered::BufWriter;
 use object_store::path::Path;
 use object_store::{ObjectStore, PutPayload};
 use parking_lot::RwLock;
+use tokio::time::sleep;
 use std::collections::{HashMap, VecDeque};
 use std::ops::Range;
 use std::sync::Arc;
+use std::time::Duration;
 use tokio::io::AsyncWriteExt;
 
 pub struct TableStore {
@@ -306,6 +308,7 @@ impl<'a> EncodedSsTableWriter<'a> {
 
     async fn drain_blocks(&mut self) -> Result<(), SlateDBError> {
         while let Some(block) = self.builder.next_block() {
+            sleep(Duration::from_millis(100)).await;
             self.writer.write_all(block.as_ref()).await?;
             self.blocks_written += 1;
         }
```

The intent was to simulate slow-ish block writes to object storage.

Then, I ran this code with the modified slatedb library:

```rust
use std::{sync::Arc, time::Duration};

use object_store::{memory::InMemory, path::Path, ObjectStore};
use slatedb::{config::{CompactorOptions, DbOptions}, db::Db};
use tokio::time::Instant;

#[tokio::main]
async fn main() {
    let object_store: Arc<dyn ObjectStore> = Arc::new(InMemory::new());
    let options = DbOptions {
        flush_ms: 100,
        manifest_poll_interval: Duration::from_millis(100),
        min_filter_keys: 10,
        l0_sst_size_bytes: 1024,
        compactor_options: Some(CompactorOptions::default()),
    };
    let kv_store = Db::open_with_opts(
        Path::from("attempt3"),
        options,
        object_store,
    )
    .await
    .unwrap();

    println!("Writing for some time");
    let mut record_count = 0;

    // write a loop that inserts 1000 keys repeatedly or a duration of 1 minute
    let start = Instant::now();
    let write_options = slatedb::config::WriteOptions {
        await_flush: false
    };

    while start.elapsed() < Duration::from_secs(10) {
        let iteration = start.elapsed().as_secs();
        for i in 0..1000 {
            kv_store.put_with_options(format!("key-{}-{}",iteration % 5, i).as_bytes(), format!("value{}", i).as_bytes(), &write_options).await;
            record_count += 1;
        }
    }

    println!("Total records written: {}", record_count);

    // Close
    kv_store.close().await.unwrap();
}
```

The application failed with the InvalidCompaction message I listed above

**Comment by criccomini** [comment]
I'm also sometimes seeing:

```
conflicting manifest version. retry write
```

at the tail end of the stdout logs (right before the "total records written" log line).

**Comment by criccomini** [comment]
From @rodesai:

> ah I think this is because I haven't yet had the compaction policy look at what compactions are running when selecting a compaction to schedule. So if it starts a compaction, and then the scheduler runs again before the compaction finishes you'll see this bug. The error is returned when the scheduler tries to schedule a compaction to a sorted run, but there's already an in-progress compaction to that sorted run.

**Comment by criccomini** [comment]
@rodesai is it possible that this issue will be solved by #96?

**Comment by criccomini** [comment]
After looking at #96 and the compaction doc, I think this issue is different. #96 is about validating that the inputs adhere to the rules set forth in the doc. This issue is just about making sure that a scheduled run does not attempt to get re-scheduled.

**Comment by rodesai** [comment]
Yeah. #96 is just meant to track adding more validation. To fix this we need to fix the compaction policy to not submit redundant compactions. I've got a patch in flight to do just this, and fill in the policy with compaction beyond just l0->compacted. So I can just take this ticket.

**Comment by rodesai** [comment]
Fixed by https://github.com/slatedb/slatedb/pull/147
