### ISSUE TITLE
Document the fact that we're using the tracing crate to generate logs/spans

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#129]
https://github.com/slatedb/slatedb/pull/126 introduces usage of the [tracing](https://docs.rs/tracing/latest/tracing/) crate to emit diagnostic logs (and eventually traces) for slatedb. We should document that we're using this crate so that users of the library know how to get log messages.

**Comment by criccomini** [comment]
SGTM. This PR should also add a "Logging" page to slatedb.io (https://github.com/slatedb/slatedb-website)

**Comment by mohnishbasha** [comment]
can i take this up?

**Comment by criccomini** [comment]
@mohnishbasha sure!

**Comment by criccomini** [comment]
@mohnishbasha the doc updates should take place on:

https://github.com/slatedb/slatedb-website

Please add a new "operations" category to docusaurus (similar to the "tutorials" category) and add a "Logging" page under it. Add some documentation saying that we're using the tracing library. Show a basic example using [`env_logger`](https://docs.rs/env_logger/latest/env_logger/) with SlateDB.

**Comment by mohnishbasha** [comment]
ptal: https://github.com/slatedb/slatedb-website/pull/26

**Comment by criccomini** [comment]
Closed in https://github.com/slatedb/slatedb-website/pull/26
