### ISSUE TITLE
Add simple compression test

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#130]
Add a simple test at sst level be added for one of the compression types? I see that the enum and specific compression is under feature flag. We should as a parametrized test that checks all compression types are working.

_Originally mentioned by @vigneshc in https://github.com/slatedb/slatedb/pull/123#discussion_r1720826676_

**Comment by wasup-yash** [comment]
what is the sst level and where is it?

**Comment by criccomini** [comment]
Sorry, I just meant test using the SSTableFormat (as opposed to the DB-level get/put methods).

**Comment by flaneur2020** [comment]
can i take this issue?
