### ISSUE TITLE
Add metrics to SlateDB

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#134]
**Is your feature request related to a problem? Please describe.**
I want to get metric visibility into SlateDB. Right now we have a story around logs (with the tracing library), but I want counters and gauges for things like cache hit rates, cache sizes, last manifest refresh, and so on.

**Describe the solution you'd like**
I'd like something that can integrate with prometheus and statsd, and has at least counters and gauges. Histograms with sampling would be nice, tool. And maybe some of the others that libraries like Dropwizard Metrics have.

**Describe alternatives you've considered**
I considered just using tracing spans and log events, and aggregating log data using ELK and the like. But this is wildly inefficient (and could impact performance) compared to emitting metric data directly.

**Comment by criccomini** [comment]
After a quick Google, it seems like the [metrics](https://github.com/metrics-rs/metrics) library is commonly used.

**Comment by flaneur2020** [comment]
synced from discussions in [discord](https://discord.com/channels/1232385660460204122/1232385660946616433/1275088799155884122):

what i like prometheus-client most is that the metrics are simply atomic variables with no networking and no buffering, the cost is pretty predictable. 

taking the idea of atomic variables as a metrics approach, a library can also be instructed with metrics like this: the library can manage a struct, such as DBStats, which includes various counters, gauges, and histograms. It does not directly export the metrics itself; instead, the outer program can retrieve DBStats and export them to Prometheus or any other metrics system as needed. no dependency, and free to use any metrics solution outside. (maybe like this? https://docs.rs/async-raft/latest/async_raft/metrics/struct.RaftMetrics.html )

**Comment by rodesai** [comment]
> taking the idea of atomic variables as a metrics approach, a library can also be instructed with metrics like this: the library can manage a struct, such as DBStats, which includes various counters, gauges, and histograms. It does not directly export the metrics itself; instead, the outer program can retrieve DBStats and export them to Prometheus or any other metrics system as needed. no dependency, and free to use any metrics solution outside. (maybe like this? https://docs.rs/async-raft/latest/async_raft/metrics/struct.RaftMetrics.html )

I like this. FWIW this is the approach that RocksDB takes as well, and then systems that use it can just export the metrics from the struct in the way they see fit. For example, Kafka Streams [exposes all the metrics using the Kafka exporter](https://github.com/apache/kafka/blob/2f0ae82d4a2205c8056b8e92a954ffbed9fa65fc/streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/RocksDBMetrics.java#L38).

**Comment by criccomini** [comment]
SGTM. Let's go with our own implementation. We did the same for Samza. I don't want to implement pluggable reporters, though. Just a data structure with our metrics that's publicly accessible to the users.

**Comment by giuseppelillo** [comment]
Assigning this to myself

**Comment by criccomini** [comment]
https://github.com/slatedb/slatedb/pull/145
