### ISSUE TITLE
fill in a more realistic compaction policy

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#135]
The current implementation of the compaction scheduler just compacts l0 to a new SR whenever it sees 4 or more L0 files. This is not going to work beyond very small databases, as the number of SRs will blow up. Filing this ticket to implement a more realistic size tiered compaction policy as described in https://github.com/slatedb/slatedb/blob/main/rfcs/0002-compaction.md

**Comment by criccomini** [comment]
(Fixed in https://github.com/slatedb/slatedb/pull/147)
