### ISSUE TITLE
support changing the compression codec on an initialized db

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#141]
Currently we do not support changing the compression mode on an already initialized DB. SSTs do not store any information about the compression codec they are written with. Therefore, if we change the compression codec, we have no way of knowing how to decompress the data in a given SST. We should:
1. write the compression codec used for a given SST into the SST's info footer
2. consult the info when reading an sst block and use the specified compression codec to decompress blocks

**Comment by Hrushi20** [comment]
Working on it :)

**Comment by Hrushi20** [comment]
Do we store the name of a codec as `String` or do we use an `Enum with an index` and store the index at end of SST folder.

**Comment by rodesai** [comment]
We can probably just model it as a flatbuffer enum, and then map the slatedb compression enum to/from the flatbuffer enum when we serialize/deserialize.

**Comment by criccomini** [comment]
Just making a note on Flatbuffer enum compatibility since enums can sometimes be tricky. Sounds like new enums can be added to the end of the list safely. Removal should be done through depreciation. So nothing too bad; sounds pretty normal.
