### ISSUE TITLE
Create an in-memory block cache

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#15]
Frequently accessed SST blocks should be cached in memory. This should dramatically improve read performance. Let's start with a simple LRU cache. See [mini-lsm for an example](https://skyzh.github.io/mini-lsm/week1-04-sst.html#task-3-block-cache).

**Comment by flaneur2020** [comment]
i'm interested in this issue. can you assign it to me if it hasn't been scheduled yet?

I'll unassign myself if I become unavailable : )

**Comment by criccomini** [comment]
@flaneur2020 Thanks for checking in! @pragmaticanon has been talking about working on this one. We're discussing it on Discord if you want to [join the conversation](https://discord.com/channels/1232385660460204122/1274425009724719216).

@rodesai pointed out that it might make more sense to start with SST caching on disk (#9), since that one gives us the OS (in-memory) page cache for free. I'm inclined to agree with him. Perhaps you want to take #9 first?

**Comment by pragmaticanon** [comment]
Taking up this issue as per discussion on discord.
