### ISSUE TITLE
Compress bloom filter bitmap in SSTs

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#152]
I noticed that we're compressing blocks and the index in `sst.rs`, but we're leaving the bloom filter uncompressed. I think we should compress it using the same logic as the block and index bytes.

**Comment by palash25** [comment]
hi @criccomini i would like to take a crack at this if no one else has picked this up

**Comment by criccomini** [comment]
@palash25 All yours! Just assigned you. :)

**Comment by palash25** [comment]
@criccomini please take a look https://github.com/slatedb/slatedb/pull/172

**Comment by criccomini** [comment]
Thanks! I'll try and get to it tomorrow. 😄
