### ISSUE TITLE
Eliminate all `print!` and `println!` calls from the codebase

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#158]
Now that we're using [tracing](https://docs.rs/tracing/latest/tracing/), SlateDB should not be printing anywhere. The codebase still has a lot of print statements left over from before. These need to get converted to tracing log calls.

**Comment by abhioncbr** [comment]
Can I give it a try? Thanks

**Comment by criccomini** [comment]
Sure! Assigning to you. 🙂

**Comment by criccomini** [comment]
@abhioncbr checking in. Are you working on this?

**Comment by mohnishbasha** [comment]
@criccomini Can I chime in for this as well?

**Comment by palash25** [comment]
hi @mohnishbasha are you still working on this?

**Comment by criccomini** [comment]
@palash25 I'm moving it to you. All yours. :)

**Comment by criccomini** [comment]
Wait, my bad. @mohnishbasha has a PR out. https://github.com/slatedb/slatedb/pull/194

**Comment by criccomini** [comment]
@palash25 I'll take control of that PR and wrap it up. Do you want to look at https://github.com/slatedb/slatedb/issues/111 ? That one is getting pretty critical now.
