### ISSUE TITLE
local sst cache eviction

### ISSUE THREAD

**Issue by flaneur2020** [slatedb/slatedb#159]
a follow up of https://github.com/slatedb/slatedb/issues/9

came across this strategy might be helpful while dealing with millions of cache files:

> Cache size (in MiB, default to 102400) and minimum ratio of free size (default 0.1). Both parameters is able to control cache size, if any of the two criteria is met, client will evict cache using the simple [2-random](https://danluu.com/2choices-eviction) strategy, i.e. randomly pick 2 blocks, and drop the one with an earlier access time. Under most real world scenarios, the overall outcome is similar to LRU algorithm, while random-2 comes with lower overhead.

from https://juicefs.com/docs/cloud/guide/cache/#data-cache

**Comment by criccomini** [comment]
Awesome! Assigned to you.

@rodesai is in the process of merging a benchmark tool in #148. Think this would be enough to run some benchmarks if you instrument the code with metrics (#145 just got merged)?
