### ISSUE TITLE
Support writing WAL to local disk instead of S3

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#162]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use a filesystem for the WAL instead of object storage. This will give me the flexibility to write the WAL locally, to EBS, or EFS. This will give me more flexibility to decide between cost, durability, and latency. If I want very lower latency and a cheaper bill, I can write the WAL to local disk and sacrifice some durability. If I want higher durability at a higher price-point, I can pay for EBS. If I want still higher durability and availability at a higher latency and price point, I can pay for EFS.

**Describe the solution you'd like**
I want to have a configuration that lets me write the WAL to the local disk instead of object storage.

**Describe alternatives you've considered**
Ignoring the async write gives me low latency at the cost of durability. But it doesn't improve my API cost. Plus, network and process failures are more common than disk failures, so the durability is worse than writing the WAL to local disk.

**Comment by giuseppelillo** [comment]
I'll happily take this

**Comment by criccomini** [comment]
@giuseppelillo Can you hold off 'til next week? I want to have some discussion with everyone about this one. @vigneshc raise [some good questions in discord](https://discord.com/channels/1232385660460204122/1232385660946616433/1279121919756734575) about this.

**Comment by criccomini** [comment]
From @vigneshc

> I think more concrete use case will help us understand it better. How would we reason about the consistency model? If the put doesn't need to be durable, it doesn't need to wait for the write by passing await_flush = false. If the durability from WAL is also not required, it can be completely disabled.
> Writing WAL to local disk could help if the process would restart in the same machine upon recovery most of the time. 
> We also have local disk cache in progress, https://github.com/slatedb/slatedb/pull/139 . Could we treat the WAL to disk as a caching problem? i.e. 1) await_flush = false 2) Write to disk cache first and copy to object_store asynchronously 3) On recovery, provide an option that uses local file as well. Files are immutable and naming is deterministic. We will still block on recovery.
> 
> It does make things more complex.

**Comment by criccomini** [comment]
> Writing WAL to local disk could help if the process would restart in the same machine upon recovery most of the time.

This is hte use case I was thinking of. It kind of sucks that every time the SlateDB process stops without a clean `.close()`, you lose any in-flight messages if you're not .await()'ing.

OTOH, like you said, if you care, you should await the write to object storage.

**Comment by criccomini** [comment]
@rodesai Curious for your thoughts on this, too.

**Comment by flaneur2020** [comment]
i think this feature can be easily implemented with simply offering another `Box<dyn ObjectStore>` for WAL, as there had already existed implementation for the `ObjectStore` trait in file system like https://docs.rs/opendal/latest/opendal/services/struct.Fs.html with https://docs.rs/object_store_opendal/latest/object_store_opendal/index.html (from @Xuanwo)

enabling a Write Back local cache for WAL's object storage might also benefits for the performance of writing WALs.

**Comment by vigneshc** [comment]
> i think this feature can be easily implemented with simply offering another `Box<dyn ObjectStore>` for WAL, as there had already existed implementation for the `ObjectStore` trait in file system like https://docs.rs/opendal/latest/opendal/services/struct.Fs.html with https://docs.rs/object_store_opendal/latest/object_store_opendal/index.html (from @Xuanwo)
> 
> with this approach, users can also choose using a fast S3 Express bucket for WAL, while using a colder & cheaper storage for the data.
> 
> enabling a Write Back local cache for WAL's object storage might also benefits for the performance on writing WALs. however, a Write Back cache can not guarantee the durability of writing unless we can disable the evictiton of these cache files, which makes it less likes "cache", but a durable local storage.

Yes, write back cache won't guarantee durability. await would have to be on the object_store store. Yes, the store used for wal can be made pluggable. Understanding the benefit SlateDB would have over local disk only store like rocks db in the environment where this configuration (WAL to local disk, rest to object store) is applicable would help get more clarity.

**Comment by vigneshc** [comment]
Is writer fencing completely disabled or not available in this config?

**Comment by criccomini** [comment]
I had been thinking it would continue to be enabled. But now that you point that out, if the writer gets a non-consecutive writer_epoch on restart, it could put the writes out of order since another writer could have appended to the WAL. 🤔 

We could discard the local WAL if we get a non-consecutive writer_epoch.

The semantics for this get really funky. We can replay the WAL only if the process starts on the same machine and no other writer writes to the WAL in the meantime.

Yea... this is feeling like it's a bad idea. 😬

**Comment by rodesai** [comment]
I'd definitely like to understand the use cases better.

I can see why this would be appealing in theory - you could basically use slatedb the same way you'd use RocksDB, except your db can grow beyond the size of disk, it's 1/3 the storage cost, you can easily share snapshots, and you could run a distributed compactor. Assuming the working set is cacheable (and we actually have a cache :)) so you don't have to go to s3 for reads often, it should work pretty well and cheaply.

I don't really see the point of fencing if you're using it this way (as a replacement for an embedded db that's local to a given vm/container). If the WAL is on local disk, then you have better options to prevent concurrent access (lock files, exclusive mounts if you're using k8s, etc).

**Comment by criccomini** [comment]
> I'd definitely like to understand the use cases better.

My initial thought was simply, "It kinda sucks that if there's an unclean shutdown of the DB, we lose any inflight data. Even if it's a simple restart." From there it went to, "Hmm, it might be nice to give users the option to put the WAL in EBS so they have faster latency and fewer API calls at the expense of a bit of durability/availability."

Not much beyond that.

> If the WAL is on local disk, then you have better options to prevent concurrent access

In the use case I was considering, I was still expecting the process to be able to be moved across machines during failures and such; similar to how we think about it now. If the process is moved, and the WAL was on local disk (not EBS), then the process is moved _back_ to the original machine, the WAL on the original machine probably has to be ditched (otherwise there are ordering issues if the other machine wrote to the WAL). That's what I was getting at.

So I guess I'm kind of mixing a lot of things: WAL on disk vs. WAL on EBS vs. WAL on EFS. Whether the WAL is meant to be accessed across processes (i.e. moving machines), etc.

This is about as far as I've gotten thinking about it. As @rodesai said, perhaps a locking mechanism on the filesystem (lock file) is good enough for EBS/EFS-based usage.

**Comment by rodesai** [comment]
@criccomini why'd we close this?

**Comment by criccomini** [comment]
Accident! 🤦‍♂️ my bad!

**Comment by flaneur2020** [comment]
some random thought:

- support WAL on local disk could make write operations much faster if one hope to trade off some durability on local node instead of object storage.
- users can also use local disk and object store together for WAl, giving a better durability than the local only WAL. 
- when use local disk & object store together, WAL should not be regarded as a **cache** in front of object storage, but a source in an async replication stream: the WAL should be replicated into object storage **in order**. like we have `0001.wal`, `0002.wal`, `0003.wal` in local, we should sync the `0001.wal` to object store first, then `0002.wal`, `0003.wal`.

(but does it worth to have the complexity to have local & remote WAL together? if we use local WAL only, the possible data loss is the MemTable size (L0 size); if use async replication to object store, the possible data loss is the replication lag between local disk & object store.)

**Comment by criccomini** [comment]
Yea, I continue to worry that this feature would add too much complexity. I've been thinking about some other approaches to achieve this:

1. We could implement an `ObjectStore` implementation that wraps an `ObjectStore` so writes go first to local disk, then are uploaded asynchronously to the wrapped store.
2. We allow users to specify the full WAL path separately from the manifest/compacted paths. This would allow users to run a local MinIO or LocalStack instance that could be used for WAL writes. (The WAL would never get synced to object storage in this case, but this might be fine if they're using EBS).
3. Perhaps the user should consider using RocksDB-cloud? I believe RocksDB-cloud works the way we're talking about.
4. We could migrate to OpenDAL. This would give us much more flexibility about the storage systems we support. In fact, it would allow us to run SlateDB entirely on filesystem, though I doubt the CAS semantics will work as we want them to.
5. User could opt to `await_durable: false`. Not quite the same as writing to local disk, since we might be able to save some local WAL writes on restart, but pretty close.

Anyhow, all of these ideas seem to achieve roughly the same goal: speeding up writes at the cost of durability. I kinda feel doing (1) and (2) would be much simpler than what we're talking about, and yield the same result.

**Comment by flaneur2020** [comment]
this makes sense, given that the lower bound of data loss is limited to L0 data size (<128MB ?), following the simpler approach provides the best benefit-to-complexity ratio.

about (4), @Xuanwo once suggested that we could consider adding an abstract I/O layer similar to [FileIO](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/io/file_io.rs) in iceberg-rust, with OpenDAL as one of the underlying implementation. This approach would allow for incremental enhancement while maintaining the `object_store` interface without breaking changes 😁.

**Comment by Xuanwo** [comment]
> about (4), @Xuanwo once suggested that we could consider adding an abstract I/O layer similar to [FileIO](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/io/file_io.rs?rgh-link-date=2024-12-20T13%3A30%3A14Z) in iceberg-rust, with OpenDAL as one of the underlying implementation. This approach would allow for incremental enhancement while maintaining the `object_store` interface without breaking changes 😁.

I would be happy to help implement this if we decide to go in this direction.

**Comment by criccomini** [comment]
@Xuanwo can OpenDAL be run a runtime other than Tokio? `object_store` is very tied to Tokio (https://github.com/apache/arrow-rs/issues/6051).

**Comment by criccomini** [comment]
> We could migrate to OpenDAL. This would give us much more flexibility about the storage systems we support. In fact, it would allow us to run SlateDB entirely on filesystem, though I doubt the CAS semantics will work as we want them to.

Now that I think about it, we don't even need to migrate. Users could run [`object_store_opendal`](https://docs.rs/object_store_opendal/latest/object_store_opendal/) if they want to put SSTs on disk. 🤯 

And if we implemented (2), users could use `object_store_opendal’ for their WAL file and an S3/GCS/whatever `object_store` for their compacted SSTs/manifests.

**Comment by criccomini** [comment]
I put up a draft patch for (1) in https://github.com/slatedb/slatedb/issues/162#issuecomment-2555944507 in #422

**Comment by criccomini** [comment]
IMO, we should close this as won't fix. We now support a separate WAL object store from the main object store (#558, #533). Users that wish to write to local storage for the WAL can do so using [LocalFileSystem](https://docs.rs/object_store/latest/object_store/local/struct.LocalFileSystem.html) or any number of OpenDAL's integrations (#639). Users can also run MinIO locally if they wish.

For storage, users can use EBS for the WAL path rather than local disks if they want stronger availability guarantees.
