### ISSUE TITLE
Support S3 CAS now that PUT `If-none-match: *` is supported

### ISSUE THREAD

**Issue by tv42** [slatedb/slatedb#164]
https://github.com/slatedb/slatedb/blob/main/rfcs/0001-manifest.md#cas-on-s3 is out of date, as S3 just recently added support for conditional PUT: 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-requests.html#conditional-writes

**Comment by rodesai** [comment]
Thanks for filing this! We definitely want to adopt this feature. We'll need the corresponding support from the object_store crate first: https://github.com/apache/arrow-rs/issues/6285. Then we should be good to go.

**Comment by criccomini** [comment]
We should update the design doc to eliminate the non-CAS solutions since S3 now supports CAS. All object stores will now work with our CAS-based design.

This is blocked on the Arrow ticket @rodesai mentions above.

**Comment by benesch** [comment]
I put up a PR upstream to add support for native S3 CAS to the `object_store` crate: https://github.com/apache/arrow-rs/pull/6682. Still waiting on reviews, but hopefully we'll have something we can use here soon.

**Comment by benesch** [comment]
Ha! Hopefully just a few more days/weeks that you have to make that confession. 😂

**Comment by criccomini** [comment]
It's merged! Now we wait for https://github.com/apache/arrow-rs/issues/6596

**Comment by benesch** [comment]
Indeed! I've got PRs up for `object_store` to add support for `If-Match`: https://github.com/apache/arrow-rs/issues/6799#issuecomment-2499713001. If all goes well we'll get both those PRs into the next release of `object_store`.
