### ISSUE TITLE
Parallel fetch WAL files on recovery

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#185]
**Is your feature request related to a problem? Please describe.**
Some users have observed slow start times on startup. I believe this is because we currently read WAL files sequentially during startup recovery. When running on a laptop, each fetch can take a while.

**Describe the solution you'd like**
I'd like to have the WALs be fetched in parallel (up to some max parallel limit) so we don't serialize the latency.

**Comment by palash25** [comment]
hi @criccomini i would like to pick this up if no one is working on this

**Comment by criccomini** [comment]
All yours! I believe @vigneshc is doing some WAL-related stuff but should be fairly minimal conflicts.

**Comment by palash25** [comment]
didn't get time to look at this the last few days, i will try to make a PR by tomorrow
