### ISSUE TITLE
db_bench: a panic with sst_iter

### ISSUE THREAD

**Issue by zamazan4ik** [slatedb/slatedb#186]
**Describe the bug**
While running `db_bench` on a local machine I get in approximately 30% of tests a panic.

**To Reproduce**

* Clone the repo
* Build `db_bench`
* Run `./db_bench_release --provider memory --path /home/zamazan4ik/open_source/slatedb/target/storage --disable-wal true write --duration 25000 --key-len 32 --val-len 256`
* See a panic (sometimes it just hangs (no CPU activity in `htop` for a long time) without a panic - also not a good thing)

**Expected behavior**
`db_bench` finishes without errors

**Screenshots**
N/A

** Build **
On Linux and Mac, please run `uname -a` to get your OS information.

 - OS: `Linux fedora 6.10.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 00:08:59 UTC 2024 x86_64 GNU/Linux`
 - SlateDB Version: locally built `db_bench` from `main`, `013e71d17712870c3a7bbd4a15e1abc771feb085` commit. Build was done with the following command: `cargo build --release --features db_bench --bin db-bench`
 - Memory provider
 - Filesystem: BTRFS
 - Rustc version: 1.80.1

**Additional context**

* Stacktrace: https://gist.github.com/zamazan4ik/5a46542595f568307d9c0371fbfcc909
* The amount of free memory (RAM) is more than enough in my case during the benchmark.

**Comment by criccomini** [comment]
Thanks for reporting this. I think only @rodesai has run db_bench, and only on S3 so far. I'll try and fiddle around with your issue later this week. If you make any headway in the meantime, please update here.

**Comment by criccomini** [comment]
I'm able to replicate this. I think it might be related to #192. They're seeing memory leakage, too.

**Comment by criccomini** [comment]
Upon further inspection, I realized this is using the in-memory object store. That's why it runs out of memory.

**Comment by criccomini** [comment]
Looking at this in more detail. I checked my logs and don't see the OOM killer killing the thread.

**Comment by criccomini** [comment]
Interestingly, debug does not fail. Only when built as a release binary.
