### ISSUE TITLE
Clean up usage of `SsTableInfoOwned` from the main db code

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#213]
**Is your feature request related to a problem? Please describe.**
We currently use the flatbuffer type for the SST metadata (`SsTableInfoOwned`) throughout the codebase when interacting with SSTs. This is not ideal:
- We shouldn't be leaking the serialized representation of the SST metadata into most modules, which don't care how the metadata is serialized.
- The flatbuffer API is a bit awkward (it uses it's own types for collections, users need to call `borrow` before using it, etc)

**Describe the solution you'd like**
We should define our own struct for the SST info, and then write a codec that converts between it and the flatbuffer format. Then, we should switch most usage of `SsTableInfoOwned` to that struct. In doing this, we can probably also get rid of `SsTableInfoOwned` and just use the codec to convert back and forth to/from fb.

**Describe alternatives you've considered**
Just leave it as is, which has the problems described above.

**Comment by criccomini** [comment]
I don't mind taking this one 🙂

**Comment by criccomini** [comment]
@rodesai WDYT about `SsTableIndexOwned` as well? Seems weird to do one without the other.

As an aside, if we go this route, I think we're abandoning the efficiency gains that FlatBuffer might give us (lazy reading). I think we might have already lost the gains through Manifest, though.

**Comment by criccomini** [comment]
Related to the above, someone from Nile did some profiling and found 60% of the time was spent in `SsTableFormat.decode_index` on read-heavy workloads. Feels like low hanging fruit we might be able to go after as part of this refactor (and the index caching in #216).

![image](https://github.com/user-attachments/assets/6e3238d4-eb56-44f2-97ec-876c28b5f910)

**Comment by criccomini** [comment]
Not to derail this whole issue, but the reason we see the flatbuffer call so much is because `DbInner`'s `get_with_options` instantiates `SstIterator::new_from_key`, which calls `new_opts`, which eventually calls `decode_index`. We're calling `flatbuffers::root` every time this happens. Not sure if this is the way FlatBuffers is meant to operate.

**Comment by criccomini** [comment]
One note here: I talked with @rodesai regarding SsTableIndexOwned replacement. Given that it's much larger, we're probably benefiting more from FlatBuffer's delayed serde. As such, we plan to leave it as a direct FlatBuffer passthrough for now rather than using the codec approach.
