### ISSUE TITLE
support providing a cache instance rather than specifying options

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#226]
**Is your feature request related to a problem? Please describe.**
Some use cases may involve creating multiple slatedb instances on a single node. This is common for cases where a single logical store is sharded over multiple slatedb stores. The shards may be collocated on a given node. In such cases, the application needs to be able to enforce some control on usage of resources like memory and disk space. Perhaps the largest consumers of these resources are the caches. In today's implementation, the application is forced to explicitly partition available memory/disk available the slatedb instances running on a given node, which may result in sub-optimal usage.

**Describe the solution you'd like**
Allow the application to instantiate the caches and pass the cache instances into slatedb, so that multiple slatedbs use a shared cache rather than having each instance use its own cache. This would require:
- Changing the db options to accept a cache instance for the block and object store caches rather than a set of options for creating a cache.
- Ensuring the ids used to identify cached objects are unique to a given slatedb instance. I think this should be the case as the SST ids are always ULID.

**Additional context**
Rocksdb takes a similar approach (see https://github.com/facebook/rocksdb/wiki/memory-usage-in-rocksdb#indexes-and-filter-blocks)

**Comment by criccomini** [comment]
@calavera mind commenting here so I can assign you?

**Comment by criccomini** [comment]
Calling out that this change is going to make some stuff public that wasn't previously (BloomFilter, SsTableIndexOwned, and so on).

**Comment by calavera** [comment]
This issue can be closed now as #231 was merged.
