### ISSUE TITLE
Create a `cargo bench` test

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#230]
**Is your feature request related to a problem? Please describe.**
I'd like to have a `cargo bench` test that I can run to verify changes don't regress performance for some basic set of use cases. This doesn't need to be fully exhaustive, and should not depend on any 3rd-party infra (S3, LocalStack, and so on).

**Describe the solution you'd like**
I'd like to be able to run `cargo bench` and get some basic metrics for common traffic patterns. Probably using the in-memory model (perhaps with some built-in randomized latency) would be enough.

**Describe alternatives you've considered**
Considered using a LocalStack Github-actions approach. This would give us a slightly more robust test, but requires remote execution. I want something local.

**Comment by AlvinKuruvilla** [comment]
Hi @criccomini, I'd like to take a stab at this. I looked over the example code for slate's README, so I understand how to create the in-memory object store. What types of traffic patterns would you like to try and emulate? Off the top of my head, I thought a flow could be a loop of 'n` puts, gets, and then deletes, and then we could see how long each component of that flow takes. I'd love to hear your vision on this, though :)

**Comment by criccomini** [comment]
H3y @AlvinKuruvilla , thanks for asking! Unfortunately, I took a look at this a few days ago and determined that the bench command is really meant for micro benchmarks, which aren't too useful to us. I documented my exploration and code exploration here:

https://github.com/slatedb/slatedb/pull/232

**Comment by criccomini** [comment]
@AlvinKuruvilla if you're looking for something related, want to grab #229? It's a specific improvement for bloom filters. It'd require writing a bench for the bloom filter and then testing the performance of murmur64 vs. our existing hash (sip).

**Comment by AlvinKuruvilla** [comment]
I will take a look, thanks @criccomini !

**Comment by criccomini** [comment]
SGTM! Mind commenting on that PR so I can assign to you?
