### ISSUE TITLE
Combine s3_bench and db_bench

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#236]
s3_bench (#233) is similar in goal and feature set to db_bench. We should merge them.

I'm not yet sure which one to start with. s3_bench has both reads and writes, and gnu plot. We definitely want that.

db_bench has a pluggable object store and key generator, and a more robust stats recorder.

_Original discussion in https://github.com/slatedb/slatedb/issues/233#issuecomment-2380248029_

**Comment by criccomini** [comment]
I took a look at https://github.com/RedisLabs/memtier_benchmark. Looks like they do both, "Random and sequential key name pattern policies"

**Comment by rodesai** [comment]
I'm ok with building off of either - its just bugging me that there's two tools that basically do the same thing. I think we should just decide what we want to run nightly and then get one of the two tools to do that. They're both pretty simple right now, so it doesn't really matter that much which one we build off of going forward.

What seems like a decent starting point for a nightly regression test to start with would be to do one test that measures how long it takes to load some number of randomly produced keys, and another test that measures the thread throughput of the database after loading it. We could do mixed workloads too, but as a first step just testing writes and reads seems like it'll give us a ton of signal. Having the gnuplots for those runs is really nice. I think the s3_bench tool sets us up nicely to do that. I do like having a more flexible key generator, and I'm much more partial to the declarative clap stuff that it does for args, but those are easy things to add.

**Comment by criccomini** [comment]
@rodesai Yea, I went back and forth last night on which one to start from 🤣 They're both like half of what I want. I'll fiddle around with it and see what sticks. I like your idea of write then read tests. I think we could actually emulate that with what @taburet has done by doing 100% preload then 100% read

Stuff from your db_bench that I think we should move over:

- Declarative clap args
- Key length
- l0 sst size and await durable settings
- Pluggable keygen

Anything else you want?

**Comment by rodesai** [comment]
> Anything else you want? I didn't include the leaky_bucket write rate stuff in the list. Think this is worth keeping?

Nah this looks good. I'm ok with leaving out the write rate stuff. I didn't wind up using it much after I got the tool bootstrapped.
