### ISSUE TITLE
weigh cache entries using block sizes in db cache impls

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#241]
**Describe the bug**
Currently the two db cache implementations (mocha and foyer) both configure static weights for the cached entries. This is not correct and will result in the caches incorrectly estimating total cache size and weights for entries (I'm not sure if/how these are used - presumably it can be used when deciding what to evict).

**Expected behavior**
We should instead use the actual size of the cached entry (e.g. block, filter or index). I think a reasonable way to implement this would be to add a `size` method to `CachedEntry` that returns the size of an entry, and then use this method to compute the weight in the closures passed to `FoyerCache::new_with_opts` and `MokaCache::new_with_opts`.

**Additional context**
See https://github.com/slatedb/slatedb/pull/231#discussion_r1779369681 for more context.

**Comment by calavera** [comment]
I can take a stab at this.
