### ISSUE TITLE
Make `DbConfig` serializable

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#263]
We're slowly encoding all of the `DbConfig` options as Clap arguments in `bencher`. It might be nice to support `DbConfig` serialization from a file instead. @agavra mentioned `.properties` files. I had been thinking of JSON/YAML/TOML encoding. Regardless of the format, something like that would be handy.

(Originally brought up in #261.)

**Comment by agavra** [comment]
+1 to JSON, happy with that and we can even make it schema'd. I'm just used to `.properties` files from my Kafka days 😆

**Comment by calavera** [comment]
I would suggest using https://docs.rs/figment/latest/figment/. It supports multiple formats and has a nice integration with Clap to make handling configuration more uniform.

**Comment by calavera** [comment]
Can you assign this issue to me? I can take a stab at it.

**Comment by calavera** [comment]
I have a first draft of this working, but I have a clarifying question before I move forward with it and create a PR. Do you want to keep all the flags that currently exist in bencher, or you'd like to replace them all with something like `--config` that loads `DbOptions` from a file directly?

There is no much difference, but keeping the current flags is extra work that I'm not sure you want to maintain.

**Comment by criccomini** [comment]
🤔 good question. I think we can get rid of the current bencher flags and just use `--config` for the `benchmark-db.sh`, it'll have to be tweaked to either generate config files or we'll have to keep a folder with the various pre-defined configs...

**Comment by criccomini** [comment]
Actually, I noticed that there are still a couple configs that aren't part of `DbOptions`. Namely, the put percentage and concurrency. I think those should be kept as params.
