### ISSUE TITLE
Db::get leaks references to underlying block

### ISSUE THREAD

**Issue by hachikuji** [slatedb/slatedb#277]
**Describe the bug**
It looks like `Db.get` currently returns a slice of the value from the underlying block that the entry was found in. The value is decoded [here](https://github.com/slatedb/slatedb/blob/75718e53ef5d10580eaef34742f64084e4a47766/src/row_codec.rs#L104) and returned [here](https://github.com/slatedb/slatedb/blob/75718e53ef5d10580eaef34742f64084e4a47766/src/db.rs#L116). This would prevent cleanup of the full block as long as the reference to the returned value remains valid. Would it be safer to make a copy?

**Comment by criccomini** [comment]
Hmm. This is where my Rust skills might be lacking. But as I understand it, we are using `Bytes` in `ValueDeletable::Value`. So, in [this line](https://github.com/slatedb/slatedb/blob/75718e53ef5d10580eaef34742f64084e4a47766/src/row_codec.rs#L104) where we call `as_slice`, it's implicitly being converted to a Bytes, which uses an ARC under the hood (i.e. it's safe to return).

The implicit conversion happens in this code, I think:

https://github.com/tokio-rs/bytes/blob/master/src/bytes.rs#L858-L862

It sounds like `from_static` directly references the slice. So perhaps we need `copy_from_slice` when creating `ValueDeletable::Value`?

**Comment by criccomini** [comment]
OTOH, maybe I'm looking in the wrong spot?`from_static` has a `'static` lifetime, so directly referencing those slices should be safe..

**Comment by criccomini** [comment]
Ok, so `BlockIterator`'s `load_at_current_off` calls `decode_row_v0`. That's where the `Bytes` come in. If you continue tracing, you'll see that the block iterator gets the cursor from a `BlockLike` object's `.data()`, which is still a `Bytes`. `spawn_fetches`,  This goes all the way to `read_blocks_using_index` in `tablestore.rs` and `read_blocks` in `sst.rs`.

**Comment by criccomini** [comment]
Perhaps you are simply suggesting that, by returning the `Bytes` in `get()`, the entire block is kept in memory until the end users release their reference to the returned value? This could create some memory pressure.

**Comment by hachikuji** [comment]
> Perhaps you are simply suggesting that, by returning the Bytes in get(), the entire block is kept in memory until the end users release their reference to the returned value? This could create some memory pressure.

Yes, that's right. I thought it might be safer to copy the value in case the user held onto it for a long time (e.g. in a cache).

**Comment by criccomini** [comment]
Gotcha. Was discussing with @stuhood on Discord as well. Sounds like there are a few options:

1. Return a copy of the Bytes.
2. Add some docs telling users to copy the Bytes if they plan to hold it for a long time.
3. Implement some kind of trimmer that will trim the Bytes once it's evicted from cache so it uses less memory.

**Comment by criccomini** [comment]
I'm in favor of (2) for now.

**Comment by hachikuji** [comment]
Sounds fair to me. I thought compaction is an area where we might see a difference adding a copy, but at least testing locally, the benchmark didn't show a differnece. In any case, documentation seems reasonable for now.
