### ISSUE TITLE
Support running the GC loop once via an admin tool

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#286]
**Is your feature request related to a problem? Please describe.**
Currently running the GC requires spawning a long-lived process. It would instead be useful to be able to schedule iterations of the loop as a periodic job or lambda invocation.

**Describe the solution you'd like**
We should support running the GC loop once and then exiting. Additionally, it would be nice to be able to execute this from the command line using the admin tool.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/slatedb/slatedb/pull/278#discussion_r1817950856

**Comment by pragmaticanon** [comment]
will take this up if no one has yet.

**Comment by criccomini** [comment]
Awesome! @pragmaticanon assigned!

**Comment by agavra** [comment]
Since it has been a while without activity on this and I had some time/desire to learn about GC I went ahead and gave it a stab #343.
