### ISSUE TITLE
Update GC to avoid deleting data referenced by checkpoints

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#311]
Update GC to avoid deleting data referenced by checkpoints as described in https://github.com/slatedb/slatedb/blob/main/rfcs/0004-checkpoints.md

This requires
1. update the GC to purge any expired checkpoints safely (the RFC details the protocol for doing this under https://github.com/slatedb/slatedb/blob/main/rfcs/0004-checkpoints.md#garbage-collector)
2. update the GC to retain manifests that are referenced by a checkpoint
3. update the GC to retain SSTs referenced by an active checkpoint

**Comment by hachikuji** [comment]
@rodesai Can I pick this up?
