### ISSUE TITLE
table driven test cases in block.rs

### ISSUE THREAD

**Issue by flaneur2020** [slatedb/slatedb#340]

**Comment by samsond** [comment]
Hi @flaneur2020 , I would like to work on this issue.

**Comment by criccomini** [comment]
@samsond Great! I just assigned it to you. Thanks. :)

**Comment by samsond** [comment]
Hi @criccomini I just pushed PR. Let me know what you think. Thanks.

**Comment by criccomini** [comment]
@samsond Looking good, thanks! I left one comment.

**Comment by samsond** [comment]
Hi @criccomini i have updated with your review, let me know once you got a chance to look into.

**Comment by criccomini** [comment]
Thanks! Will take a look. Might be slow because of the holiday.
