### ISSUE TITLE
Make `DbOptions` `Debug` and log on JSON encode failure

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#347]
While working on https://github.com/slatedb/slatedb/pull/344, I tried to log `DbOptions` using `{:?}` but it failed because `DbOptions` doesn't currently have `Debug` set. It'd be nice to:

1. work through the options and enable `Debug` for everything
2. update this log line (https://github.com/slatedb/slatedb/pull/344/files#diff-7d7d3a6ce5c2a3e8b39ce4f49b78a71365c8e06c0d9ddb78bc2dca68bfeb4a5bR586) to print the `options` object.

**Comment by calavera** [comment]
I made a quick change in https://github.com/slatedb/slatedb/pull/351
