### ISSUE TITLE
Integrate regression benchmarking with CI/CD Process

### ISSUE THREAD

**Issue by agavra** [slatedb/slatedb#370]
**Is your feature request related to a problem? Please describe.**
@dmvk noticed a performance regression in 0.3 related to #325 - this was only caught manually.

**Describe the solution you'd like**
We should make sure that:
- at minimum, we run benchmarks manually before release (update RELEASE.md)
- ideally, we run automated benchmarks and report them somewhere (perhaps publicly on the website as hinted at on #165) on some cadence so that we can more easily find regressions

**Describe alternatives you've considered**
We can consider running it per-commit, but that would cause a significant overhead in the PR-review latency cycle, which I think we should be sensitive about.

**Additional context**
see: https://github.com/slatedb/slatedb/issues/371

**Comment by agavra** [comment]
https://github.com/benchmark-action/github-action-benchmark might be an interesting option to look into, it'll automatically run `cargo bench` nightly

**Comment by criccomini** [comment]
@agavra Oh, that second link (Quansight) is interesting. I'd been considering plugging into architect.run so we could get baremetal.

At a high level, I think we need to have a multi-pronged approach to this. The bench stuff is meant for little microbench perf tests. I think that might be OK to run as part of the CI/CD even. This would be good for @dmvk's benchmark that he shared.

OTOH, as you said, the `bencher` stuff is more long running and should probably run nightly. I think that could serve two purposes: 1) failing if the perf regresses beyond some threshold 2) recording and publishing the performance results so we can see them in the browser.

That's how I'd been thinking about it.

Longer-term, I'd like to set up AWS (and perhaps other providers) accounts so we can test against actual buckets. This was one of the appealing things about architect.run-- I think it's supposed to run in AWS/GCP/etc. But in the short term, I was thinking we'd just use `object_store`'s local FS and/or localstack's S3.

**Comment by criccomini** [comment]
@agavra I took #165. I think it has significant overlap with this (if not an outright dupe). I wrote a comment (https://github.com/slatedb/slatedb/issues/165#issuecomment-2518435319) describing what I intend to do. If that looks OK and this issue is a dupe, LMK and we can close this and I'll get cracking on #165.

**Comment by agavra** [comment]
🫡 - I was thinking that the easiest way to "close" this issue is just to update the `RELEASE.md` with "run the benchmarks, please" but if you're going to do the automation as part of #165 that definitely subsumes this one. Feel free to close it!
