### ISSUE TITLE
Add range scan examples to README.md and slatedb-website

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#409]
Now that #342 is merged, we should show users how to use range scans. This issue tracks:

- [ ] Update slatedb-website's [quickstart](https://slatedb.io/docs/quickstart) to show range scan usage
- [ ] Update README.md to show range scan usage.

**Comment by jeffreylean** [comment]
I would like to take on this while I try to understand how range scan works in slateDB

**Comment by criccomini** [comment]
Great! Thank you 😊 assigned
