### ISSUE TITLE
Discord link is not working

### ISSUE THREAD

**Issue by jeffreylean** [slatedb/slatedb#416]
I would like to join the discord group but the link in the website is no longer working, likely expired.

**Comment by criccomini** [comment]
Oh no! Let me check

**Comment by criccomini** [comment]
Which link are you referring to? I checked the SlateDB.io link and the bandage on the readme. Both seem ok.

**Comment by jeffreylean** [comment]
Ohh the link works when I use another browser to open it, might be some setting I've with my browser that causes this.
