### ISSUE TITLE
Update "Connect SlateDB to S3" documentation and remove dynamodb 

### ISSUE THREAD

**Issue by vigneshc** [slatedb/slatedb#424]
**Describe the bug**
DynamoDB is no longer required for conditional puts, starting from 0.4.0. Try out S3 without dynamo db details and then update [documentation](https://slatedb.io/docs/tutorials/s3).

Documentation is in this [file](https://github.com/slatedb/slatedb-website/blob/main/docs/tutorials/s3.md)

**Comment by criccomini** [comment]
I've updated the docs in this PR:

https://github.com/slatedb/slatedb-website/pull/28

**Comment by criccomini** [comment]
I merged optimistically. LMK if you spot anything off.
