### ISSUE TITLE
Implement an `ObjectStore` with our desired S3 semantics

### ISSUE THREAD

**Issue by paulgb** [slatedb/slatedb#45]
The rust `object_store` crate, which is the abstraction we use for object storage, supports reaching out to a DynamoDB to implement [conditional put](https://docs.rs/object_store/latest/object_store/aws/enum.S3ConditionalPut.html) and [copy if not exist](https://docs.rs/object_store/latest/object_store/aws/enum.S3CopyIfNotExists.html) semantics.

The implementation is based on time-based leases, which has a problem of slow writes when a lock timeout needs to be waited upon, and also potentially a zombie writer problem. That said, we can use the pattern of implementing CAS semantics in the object store itself to implement CAS with DynamoDB using the other approaches we have specced out.

By implementing the CAS semantics in the object store layer itself, there will be less S3-specific code in SlateDB itself, and it will be easy to swap out if (when?) S3 implements CAS natively.

[relevant Discord discussion](https://discord.com/channels/1232385660460204122/1232385660946616433/1237832940554293308)

**Comment by criccomini** [comment]
Woohoo! We don't need to do this anymore. S3 now has put-if-not-exists:

https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/
