### ISSUE TITLE
Add range queries

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#8]
Add range queries to Db and DbInner. I'm thinking we'll copy RocksDB's interface, which has a `db.iter()` and `iter.seek()` API.

At a high level, I think this work involves a few things:

1. Creating a snapshot manager that creates, updates, and deletes snapshots from the manifest.
2. Cloning the current DB state, including the memtables and wal data structures. This will be needed for the iterator, so it has a consistent point in time to iterate over all data (both in-memory and on disk/obj storage). I'm thinking this might be included as part of the snapshot manager (i.e. each snapshot in the manager will be a full `Db` with a state at a point in time).
3. Creating a user-facing `DbIterator` that merges the wal, memtable, and L0+ SSTs into a single iterator similar to `MergeIterator`. We might be able to use `MergeIterator` directly, I need to check. This iterator interface should have a `seek()` method.
4. Update the `Db` object to have a `.iterator()` method that returns a `DbIterator`.

For (3), I suspect if we use `MergeIterator`, we'll need a DbMergeIterator (similar to TwoMergeIterator) that takes iterators for wals, memtables, and SSTs (because of the Rust typing issue mentioned [here](https://github.com/slatedb/slatedb/pull/98#issue-2424526679)

I don't plan to tackle `prev()` in this issue.

**Comment by criccomini** [comment]
@paulgb Pulled you from this one since it's been a few months. LMK if you want to pick it back up.

**Comment by criccomini** [comment]
At a high level, I think this work involves a few things:

1. Creating a snapshot manager that creates, updates, and deletes snapshots from the manifest.
2. Cloning the current DB state, including the memtables and wal data structures. This will be needed for the iterator, so it has a consistent point in time to iterate over all data (both in-memory and on disk/obj storage).
3. Creating a user-facing `DbIterator` that merges the wal, memtable, and L0+ SSTs into a single iterator similar to `MergeIterator`. We might be able to use `MergeIterator` directly, I need to check. This iterator interface should have a `seek()` method.
4. Update the `Db` object to have a `.iterator()` method that returns a `DbIterator`.

For (3), I suspect if we use `MergeIterator`, we'll need a DbMergeIterator (similar to TwoMergeIterator) that takes iterators for wals, memtables, and SSTs (because of the Rust typing issue mentioned [here](https://github.com/slatedb/slatedb/pull/98#issue-2424526679)

I don't plan to tackle `prev()` in this issue.

**Comment by timfish** [comment]
`DoubleEndedIterator` would be nice so you can iterate through the range in either direction!

**Comment by criccomini** [comment]
Fixed in:

https://github.com/slatedb/slatedb/pull/342

**Comment by criccomini** [comment]
Closing since #342 is merged.
