### ISSUE TITLE
Avoid locking db state for every key-value pair when replaying the WAL

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#86]
Currently we are locking DbState for every kv pair when replaying the WAL. This is somewhat inefficient, and could increase replay times if there are lots of keys. We could easily optimize this by either:
1. detaching this method from self and calling it before initializing DbInner. The downside is we can't use member methods of DbInner like maybe_freeze_wal
2. accumulating kv-pairs in memory and bulk-applying the writes

**Comment by flaneur2020** [comment]
can i take this issue?

**Comment by criccomini** [comment]
@flaneur2020 Sure, thing. I've assigned to you. :) thanks!
