### ISSUE TITLE
Move the SST index out from SsTableInfo and into its own block

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#88]
Currently we store the SST's block index directly in SsTableInfo. The block index can be quite large as it stores the first key for every block, and we currently use 4K blocks. This is bad because we store SsTableInfo in the manifest for every SST, which will blow up the manifest's size. It would be better to move the index into it's own block, and put a pointer to that block in SsTableInfo.

**Comment by Hrushi20** [comment]
Hey! I'm interested in working on this issue. Can you give me more context on ` pointer to that block in SsTableInfo.`

**Comment by rodesai** [comment]
> Can you give me more context on  pointer to that block in SsTableInfo.

Sure. [SsTableInfo](https://github.com/slatedb/slatedb/blob/9cba7800dc939a205a2310f2eb8f0dfb88c71ba7/schemas/sst.fbs#L12) defines the schema of our SST metadata. We put this metadata in the manifest for every SST, and in the SST footer. Currently SsTableInfo includes the index (also called block metadata), which includes the offset and first key for each block. This means that the index can be quite large. Consider a 1GB SST with 16K blocks and 32 byte keys - you'd have 65536 blocks, and a ~2.6MB index. We don't want to store that in SsTableInfo. Instead, we want to store it somewhere else in the SST (probably just before SsTableInfo) and then put the offset and size in SsTableInfo.

So, an SST would look like this:
[data block 1]
[data block 2]
...
[data block n]
[filter block]
[index block]
[sstinfo] (includes the offset and length of the index block)

We already do this for the bloom filter, so you could use that as an example.

**Comment by Hrushi20** [comment]
``` rust
pub(crate) struct EncodedSsTable {
    pub(crate) block: VecDeque<BlockMeta>,          // Here I'll add the blockMeta required. 
    pub(crate) info: SsTableInfoOwned,
    pub(crate) filter: Option<Arc<BloomFilter>>,
    pub(crate) unconsumed_blocks: VecDeque<Bytes>,
}
```

Approach: 

* I will create the BlockMeta struct in `SST.rs` file. It will contain the start_byte and offset. 
* Update the manifest file to take in block_meta_offset and block_meta_length.
* Update the read_block, decode_block and mechanism to write to sst files.

**Comment by rodesai** [comment]
That sounds good at a high level!

> Update the read_block, decode_block
You shouldn't need to actually modify the block read/write code to do this. I'm not proposing we put the index in a `struct Block` - that's really meant to store the db rows. I'm just proposing we take the current `block_meta: [BlockMeta]` field in `SsTableInfo` and serialize that seperately and put it in front of SsTableInfo in the SST file.

**Comment by criccomini** [comment]
@Hrushi20 Assigned the issue to you. Thanks! :)

**Comment by rodesai** [comment]
@Hrushi20 do you mind if I pick this up? It's currently blocking some other work.

**Comment by Hrushi20** [comment]
Okay. Sure

**Comment by Hrushi20** [comment]
Hey if you haven't started working on it I'll try raising an MR in couple of hours?

**Comment by rodesai** [comment]
I really needed it since I'm trying to populate a large db, so I put up a PR for it already: https://github.com/slatedb/slatedb/issues/88
This would be a good issue to pick up: https://github.com/slatedb/slatedb/issues/141

**Comment by rodesai** [comment]
fixed by https://github.com/slatedb/slatedb/pull/140
