### ISSUE TITLE
Lazily load bloom filters for SSTs

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#89]
Currently we load the bloom filter for every SST when opening the SST's handle. This is problematic because it means that we will need to load filters to load the db's core metadata, which can lead to slow db startup times. A better approach would be to do the following:
1. Decouple loading the filters from loading the SST's handle. Once this is done, we should be able to load all SST metadata from the manifest alone. This also means we need a place to store bloom filters, as currently we are storing them in the handle. A natural place to put them is in the db's cache. We could also just store them in the handle as we do today, but load them after the handle is created.
2. Initially, we can simply load the filters as reads come in that need to use them.
3. To optimize db warm up time we can load the filters in the background after starting up the db.

**Comment by Hrushi20** [comment]
Hey! As a beginner can I work on this issue? Interested to contribute to design and code.

**Comment by criccomini** [comment]
@Hrushi20 Thanks for checking.

The bloom filter has already been decoupled from the SsTableHandle. This is the first part that @rodesai mentions in (1).

Right now, we cache the filters explicitly in `TableStore.filter_cache`. As @rodesai suggests above, we should be using a generic block cache for this. That generic block cache is being worked on in #137 right now. Morever, @flaneur2020 is working on an on-disk SST cache that will further cache bloom filters on disk (as part of the SST).

I think, until at least #137 is done, it's best to hold off on this ticket. There's [active discussion](https://github.com/slatedb/slatedb/pull/137#discussion_r1728397369) about adding cache features to make this ticket easier. Until that's done, let's wait.

@Hrushi20 perhaps you want to take a look at #111? It's something we need, but haven't gotten around to yet. I don't have a clear idea on how best to do it, so it would be good to discuss a bit in the ticket.

**Comment by rodesai** [comment]
I don't think there's any additional work that's required here. We now read the filter only if it's not present in the db cache. I don't think we should jump to pre-warming the cache with filters at this point.
