### ISSUE TITLE
Add some logging infra to SlateDB

### ISSUE THREAD

**Issue by rodesai** [slatedb/slatedb#90]
We currently just log things by calling print!. We should instead convert print messages to calls to rust's logging facade (https://docs.rs/log/latest/log/) using the appropriate log level. Finally, we should set up some default logging implementation, like logging to stderr.

**Comment by criccomini** [comment]
Based on this:

https://x.com/criccomini/status/1823519434017046759

The recommended library is:

https://crates.io/crates/tracing

**Comment by dharanad** [comment]
just went through the codebase, really liked the implementation and i would like to contribute, so can I pick this up? 
This should help me understand the codebase better

**Comment by criccomini** [comment]
@dharanad absolutely! Thank you :)

**Comment by paulgb** [comment]
+1 for `tracing`!
